TODO Thibo (Guter Link: https://medium.com/@lvthillo/customize-your-mysql-database-in-docker-723ffd59d8fb)

- Neue Dockerfile basierend auf MySQL Base Image
- Alle SQL Files inkludieren und ausführen lassen
- In docker-compose.yaml im Verzeichnis oberhalb einfügen + ein Passwort definieren
